Fix compilation error caused by invalid type coercion:
$ gradle build

> Task :compileJava FAILED
/home/amiller/IdeaProjects/scelight/src-app/hu/scelight/gui/page/replist/RepListComp.java:197: error: incompatible types: Vector<Vector> cannot be converted to Vector<Vector<Object>>
                                                                        final Vector< Vector< Object > > data = model.getDataVector();
                                                                                                                                   ^
/home/amiller/IdeaProjects/scelight/src-app/hu/scelight/gui/dialog/RenameRepsDialog.java:164: error: incompatible types: Vector<Vector> cannot be converted to Vector<Vector<Object>>
                                final Vector< Vector< Object > > data = srcTable.getXTableModel().getDataVector();
                                                                                                               ^
/home/amiller/IdeaProjects/scelight/src-launcher/hu/sllauncher/gui/comp/table/XTableToolBar.java:187: error: incompatible types: Vector<Vector> cannot be converted to Vector<Vector<Object>>
                                                        final Vector< Vector< Object > > dataVector = params.getTable().getXTableModel().getDataVector();
                                                                                                                                                      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors